<?php

namespace App\Service;

use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\File\File;

/**
 * The main role of this service is to handle file loading:
 *  - generate new file names
 *  - manage their storage
 */
class UploadedFileManager
{
    private $rootDirectory;

    public function __construct($rootDirectory)
    {
        $this->rootDirectory = $rootDirectory;
    }
  
    /**
     * @return string
     */
    public function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }

    /**
     * generate unique names for docs and manage their storage
     * @return array
     */
    public function docsInputManager($docs)
    {
        $arrayOfDocs=[];

        if (!empty($docs)) {
            foreach ($docs as $file) {
                $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
                $arrayOfDocs[] = $fileName;
                // Move the file to the directory where images are stored
                try {
                    $file->move(
                      $this->rootDirectory. '/public/uploads/images',
                      $fileName
                  );
                } catch (FileException $e) {
                    // ... handle exception if something happens during file upload
                }
            }
        }

        return $arrayOfDocs;
    }
}
