version: "3"

services:
    nginx:
        build: docker/nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/usr/share/nginx/html
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx/ssl/localhost.pem:/etc/nginx/ssl/localhost.pem
            - ./docker/nginx/ssl/localhost-key.pem:/etc/nginx/ssl/localhost-key.pem

    composer:
        container_name: composer
        build: docker/composer
        tty: true
        stdin_open: true
        user: composer
        working_dir: /home/composer
        volumes:
            - .:/home/composer

    php:
        container_name: php
        build: docker/php
        tty: true
        stdin_open: true
        working_dir: /usr/share/nginx/html
        user: php
        ports:
            - 8000:8000
        volumes:
            - .:/usr/share/nginx/html

    blackfire:
        image: blackfire/blackfire
        ports: ["8707"]
        environment:
            BLACKFIRE_SERVER_ID: 6628843c-8f71-4063-90f4-37d2f4dc14eb
            BLACKFIRE_SERVER_TOKEN: e653f92f03b8849d5adfdfa40053291243b5bc61ef787c76a6fe9797eed0142f
            BLACKFIRE_CLIENT_ID: 016d2126-1a82-4a96-ab87-ab4ee9f04e90
            BLACKFIRE_CLIENT_TOKEN: eca1753e84e933a11c5731c3d942d239c73c778b192c26d54cd28ba3b1e09d0a

    # docker-compose up mariadb
    mariadb:
        restart: always
        container_name: mariadb
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
        volumes:
            - ./mariadb:/var/lib/mysql

    # docker-compose exec vegeta sh -c 'echo "GET http://php:8000" | vegeta attack -duration=10s -rate=40 | vegeta plot > plot.html'
    vegeta:
        container_name: vegeta
        build: docker/vegeta
        user: vegeta
        tty: true
        stdin_open: true
        working_dir: /home/vegeta
        volumes:
          - .:/home/vegeta
