version: "3"

services:
    nginx:
        build: nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/usr/share/nginx/html
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/ssl/localhost.pem:/etc/nginx/ssl/localhost.pem
            - ./nginx/ssl/localhost-key.pem:/etc/nginx/ssl/localhost-key.pem

    # docker-compose run --rm composer install
    composer:
        container_name: composer
        build: docker/composer
        tty: true
        stdin_open: true
        user: composer
        working_dir: /home/composer
        volumes:
            - .:/home/composer

    # docker-compose run --rm php bin/console list
    # docker-compose run --rm --service-ports php bin/console server:run --host 0.0.0.0 --port 8000
    php:
        container_name: php
        build: php
        tty: true
        stdin_open: true
        working_dir: /usr/share/nginx/html
        user: php
        ports:
            - 8000:8000
        volumes:
            - .:/usr/share/nginx/html

    # docker-compose up mariadb
    mariadb:
        restart: always
        container_name: mariadb
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: database
        volumes:
            - ./mariadb:/var/lib/mysql

    # docker-compose exec vegeta sh -c 'echo "GET http://php:8000" | vegeta attack -duration=10s -rate=40 | vegeta plot > plot.html'
    vegeta:
        container_name: vegeta
        build: docker/vegeta
        user: vegeta
        tty: true
        stdin_open: true
        working_dir: /home/vegeta
        volumes:
          - .:/home/vegeta
